---
abstract: 'Test module to see PAUSE functionality'
author:
  - 'Benjamin Wuthrich <benjamin@example.com>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4212, CPAN::Meta::Converter version 2.143240'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Acme-BEWUETHR-Utils
provides:
  Acme::BEWUETHR::Utils:
    file: lib/Acme/BEWUETHR/Utils.pm
    version: '0.04'
resources:
  license: http://opensource.org/licenses/artistic-license-2.0.php
version: '0.04'
